[package]
name = "image-moments"
version = "0.2.0"
edition = "2021"
authors = ["Christopher Gundler <christopher@gundler.de>"]
description = "Efficient and compile-time checked calculations of image moments"
license = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
approx = "0.5"
